version: '3.7'

services:

  db:
    build:
      context: ./db
    env_file:
      - ./docker-env/development.env
    ports:
      - 5436:5432
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql-data:/var/lib/postgresql/data

  backend:
    restart: always
    build:
      context: backend/
    env_file:
      - ./docker-env/development.env
    ports:
      - 5001:5000
    volumes:
      - ./backend:/app
    depends_on:
      - db

volumes:
  postgresql:
  postgresql-data:
