version: '3.7'

services:

  db:
    build:
      context: ./db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=geonames
    ports:
      - 5436:5432
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql-data:/var/lib/postgresql/data

  api:
    restart: always
    build:
      context: ./api/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - FLASK_ENV=development
      - APP_SETTINGS=config.DevelopmentConfig
      - DATABASE_URL=postgresql://postgres:admin@db:5432/geonames
      - DATABASE_URL_TEST=postgresql://postgres:admin@db:5432/geonames_test
      - GEONAMES_DATA=allCountries
      - SECRET_KEY=houdini
    ports:
      - 5001:5000
    volumes:
      - ./api:/app
    depends_on:
      - db

volumes:
  postgresql:
  postgresql-data:
